### ISSUE TITLE
README instructions do not explain credentials.json

### ISSUE THREAD

**Issue by manuelzander** [hyperqueryhq/whale-bigquery-public-data#2]
I followed the instructions in the README and the result is:

```
❯ cat connections.yaml
---
name: bq-1
metadata_source: Bigquery
key_path: ~/credentials.json
project_credentials: ~
project_id: bigquery-public-data
```

Then I ran:

```
❯ ipython
Python 3.8.6 (default, Oct 27 2020, 08:56:44)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import whale as wh
   ...: wh.pull()
```

As expected, this fails with `FileNotFoundError: [Errno 2] No such file or directory: '/Users/manuelzander/credentials.json`.

I was able to fix it by using a key file I created using my own GCP project. Is this expected from users?
I would add some points to the README explaining how to create a `credentials.json` and which GCP roles and permissions are needed 😊

**Comment by rsyi** [comment]
Ah sorry @manuelzander - I completely missed this issue.

So this happens because you're running `wh.pull()` from the python client, but `wh git-enable` (from the README) enables a flag that is caught only by the command-line tool, which redirects the command to `git pull` (basically) from the configured github repo instead of running the scraping job again.

But as you've pointed out, the fact that this logic lives inside of rust, not python, is probably sub-optimal. I'll open a new issue in the main repo. :) Thanks for pointing this out!

**Comment by rsyi** [comment]
Actually, on second thought, this would break this repo, because then there would be no way to pull directly from the sources using the `connections.yaml` file.

I'll follow your suggestion instead, and simply update the docs. :) If, locally, you want to re-pull the data, you can just run the command-line alias instead, `wh pull`.
